# roles/linux-install-docker/vars/main.yml

docker_repository_gpg_key_debian: 'https://download.docker.com/linux/debian/gpg'
docker_apt_repository_debian: 'deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'

docker_repository_gpg_key_ubuntu: 'https://download.docker.com/linux/ubuntu/gpg'
docker_apt_repository_ubuntu: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

docker_yum_repository_centos: 'https://download.docker.com/linux/centos/docker-ce.repo'

docker_compose_version: '1.28.2'
docker_compose_binary: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
