# linux-install-powerdns/tasks/ubuntu.yml

---
- name: ubuntu - add apt repository
  apt_repository:
    repo: '{{ powerdns_apt_repository_ubuntu }}'
    filename: 'powerdns'
    state: present
    update_cache: no
  tags:
    - linux-install-powerdns


- name: ubuntu - copy preferences apt files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'apt_pdns.preferences', dest: '/etc/apt/preferences.d/powerdns' }
  tags:
    - linux-install-powerdns


- name: ubuntu - add official repository key
  apt_key:
    url: '{{ powerdns_repository_gpg_key_debian_ubuntu }}'
    state: present
  tags:
    - linux-install-powerdns


- name: ubuntu - install powerdns
  apt:
    name: pdns-server
    state: latest
    update_cache: yes
  tags:
    - linux-install-powerdns