# linux-install-zabbix-agent/tasks/centos.yml

---
- name: centos - install repository
  yum:
    name: "{{ zabbix_repo_centos }}"
    state: present
  tags:
    - linux-install-zabbix-agent


- name: centos - install zabbix-agent
  yum:
    name: zabbix-agent
    state: latest
    update_cache: yes
  tags:
    - linux-install-zabbix-agent