# linux-install-zabbix-agent/tasks/debian.yml

---
- name: debian - install libcurl3 for jessie or stretch
  apt:
    name: libcurl3
    state: present
  when: ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9'
  tags:
    - linux-install-zabbix-agent


- name: debian - install libcurl4 for buster
  apt:
    name: libcurl4
    state: present
  when: ansible_distribution_major_version == '10'
  tags:
    - linux-install-zabbix-agent


- name: debian - install repository
  apt:
    deb: '{{ zabbix_repo_debian }}'
  tags:
    - linux-install-zabbix-agent


- name: debian - install zabbix-agent
  apt:
    name: zabbix-agent
    state: latest
    update_cache: yes
  tags:
    - linux-install-zabbix-agent